### PR TITLE
Update Vagrant and other updates

### PR DESCRIPTION
**Pull request by rouault**
This goes to the point where the non-binding tests pass on Vagrant and the github action, but fail on the later on the "php-testcase" . I'm not knowledgeable enough of PHP to debug this

@jbo-abs in https://github.com/jmckenna/MapServer/commit/54f0e01e2bab433f8662e6eede99513f63214d13, I've updated 2 expected results to something that is likely not correct. It seems the issue is with the rendering of ship.svg. I'm not sure if the SVG is faulty or if this is a software issue with the new versions of librsvg used by ubuntu 20.04 . Asking you as I believe you've added this in 03d5affd8a27524610b3526781eb3d3393291f5e

### CODE REVIEW

**Comment by jbo-ads** [comment]
I'll look at it as soon as possible. I hope it is just a bug in the SVG.

**Comment by jmckenna** [comment]
thanks @rouault & @jbo-ads , merging this into the main PullRequest for now (with the SLD workaround).    (I too battled those ship.svg errors, for too long, ha)

**Comment by jbo-ads** [comment]
About that ship.svg, I found a bug in the file itself. When fixed, the test involving MapFile alone passes.

I am still stuck on tests involving SLD. Observing traces from python HTTP server, they don't seem to even try to GET the SVG file. Has something around VALIDATION changed recently?

**Comment by jmckenna** [comment]
it could also just be the newer Python version (and its http server) on Focal.  I wonder if we should just comment-out that url test, for now?  When I was battling this, I noticed that that test had been commented out in the past.

**Pull request merged**
